# Generated by Django 3.1.5 on 2021-03-31 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField(blank=True, default='FHA', null=True)),
                ('price', models.IntegerField(blank=True, default=200000, null=True)),
                ('down_payment', models.FloatField(blank=True, default=3.5, null=True)),
                ('rate', models.FloatField(blank=True, default=4.0, null=True)),
                ('HOA_dues', models.FloatField(blank=True, default=0, null=True)),
                ('monthly_payment', models.FloatField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, default=360, null=True)),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
